### ISSUE TITLE
git最新版 突然出现BUG

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#1189]
## Describe the bug

突然 不能使用

## Version

git 最新版

## Screenshots
![screenshots](https://user-images.githubusercontent.com/900786/205431833-7a00498c-c31c-455d-8136-563315ef79ab.gif)

**Comment by baiheinet** [comment]
白屏时，是以下错误
![image](https://user-images.githubusercontent.com/900786/205432198-e4cc58b9-48aa-4917-96ec-6b46654fc9ca.png)

**Comment by baiheinet** [comment]
突然发现 点击两次就正常
![screenshots](https://user-images.githubusercontent.com/900786/205432725-37002cf3-e1b2-4057-b7e0-106bf916dd87.gif)

**Comment by chenos** [comment]
排查一下是不是修改了源码，如果没有重新安装依赖再试试。main 分支也有 docker 镜像的 `nocobase/nocobase:main`，没有截图的问题。

```yml
version: "3"
networks:
  nocobase:
    driver: bridge
services:
  app:
    image: nocobase/nocobase:main
    networks:
      - nocobase
    environment:
      - LOCAL_STORAGE_BASE_URL=/storage/uploads
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - "13000:80"
```
