### ISSUE TITLE
docker-compose 启动后，访问13000端口为Not Found

### ISSUE THREAD

**Issue by bonashen** [nocobase/nocobase#1336]
## Describe the bug

如题

## Version

v0.8.1-alpha.4

## app logs

```bash
~/docker-projects/nocobase/docker/app-sqlite$ docker-compose logs app
Attaching to app-sqlite_app_1
app_1  | nginx started
app_1  | copying...
app_1  | yarn run v1.22.19
app_1  | $ nocobase start --quickstart
app_1  | Connection has been established successfully.
app_1  | Start installing NocoBase
app_1  | Database dialect: sqlite
app_1  | Initialize all built-in plugins
app_1  | Reload the application configuration
app_1  | Connection has been established successfully.
app_1  | upgrading...
app_1  | Reload the application configuration
app_1  | { event: 'migrating', name: 'nocobase/2022-del-sample-plugins' }
app_1  | {
app_1  |   event: 'migrated',
app_1  |   name: 'nocobase/2022-del-sample-plugins',
app_1  |   durationSeconds: 0.014
app_1  | }
app_1  | {
app_1  |   event: 'migrating',
app_1  |   name: 'collection-manager/20220613103214-alert-sub-table'
app_1  | }
app_1  | {
app_1  |   event: 'migrated',
app_1  |   name: 'collection-manager/20220613103214-alert-sub-table',
app_1  |   durationSeconds: 0.008
app_1  | }
app_1  | {
app_1  |   event: 'migrating',
app_1  |   name: 'collection-manager/20220704225714-drop-foreign-keys'
app_1  | }
app_1  | {
app_1  |   event: 'migrated',
app_1  |   name: 'collection-manager/20220704225714-drop-foreign-keys',
app_1  |   durationSeconds: 0.009
app_1  | }
app_1  | {
app_1  |   event: 'migrating',
app_1  |   name: 'collection-manager/20221101111110-update-foreign-fields'
app_1  | }
app_1  | {
app_1  |   event: 'migrated',
app_1  |   name: 'collection-manager/20221101111110-update-foreign-fields',
app_1  |   durationSeconds: 0.008
app_1  | }
app_1  | {
app_1  |   event: 'migrating',
app_1  |   name: 'collection-manager/20221104151410-update-collections-hidden'
app_1  | }
app_1  | {
app_1  |   event: 'migrated',
app_1  |   name: 'collection-manager/20221104151410-update-collections-hidden',
app_1  |   durationSeconds: 0.007
app_1  | }
app_1  | {
app_1  |   event: 'migrating',
app_1  |   name: 'collection-manager/20221121111110-update-fk-type'
app_1  | }
app_1  | {
app_1  |   event: 'migrated',
app_1  |   name: 'collection-manager/20221121111110-update-fk-type',
app_1  |   durationSeconds: 0.008
app_1  | }
app_1  | {
app_1  |   event: 'migrating',
app_1  |   name: 'collection-manager/20221121111113-update-id-to-bigint'
app_1  | }
app_1  | {
app_1  |   event: 'migrated',
app_1  |   name: 'collection-manager/20221121111113-update-id-to-bigint',
app_1  |   durationSeconds: 0.009
app_1  | }
app_1  | {
app_1  |   event: 'migrating',
app_1  |   name: 'collection-manager/20221221103220-timestamps'
app_1  | }
app_1  | {
app_1  |   event: 'migrated',
app_1  |   name: 'collection-manager/20221221103220-timestamps',
app_1  |   durationSeconds: 0.008
app_1  | }
app_1  | {
app_1  |   event: 'migrating',
app_1  |   name: 'sequence-field/20221207022250-sequence-field-key'
app_1  | }
app_1  | {
app_1  |   event: 'migrated',
app_1  |   name: 'sequence-field/20221207022250-sequence-field-key',
app_1  |   durationSeconds: 0.008
app_1  | }
app_1  | {
app_1  |   event: 'migrating',
app_1  |   name: 'workflow/20221129153547-calculation-variables'
app_1  | }
app_1  | {
app_1  |   event: 'migrated',
app_1  |   name: 'workflow/20221129153547-calculation-variables',
app_1  |   durationSeconds: 0.009
app_1  | }
app_1  | { event: 'migrating', name: 'users/20220818072639-add-users-phone' }
app_1  | {
app_1  |   event: 'migrated',
app_1  |   name: 'users/20220818072639-add-users-phone',
app_1  |   durationSeconds: 0.009
app_1  | }
app_1  | { event: 'migrating', name: 'audit-logs/202206160949-logging' }
app_1  | {
app_1  |   event: 'migrated',
app_1  |   name: 'audit-logs/202206160949-logging',
app_1  |   durationSeconds: 0.006
app_1  | }
app_1  | ✨  NocoBase has been upgraded to v0.8.1-alpha.4
app_1  | 2023-01-07T02:40:04: PM2 log: Launching in no daemon mode
app_1  | 2023-01-07T02:40:05: PM2 log: App [index:0] starting in -fork mode-
app_1  | 2023-01-07T02:40:05: PM2 log: App [index:0] online
app_1  | Connection has been established successfully.
app_1  | 🚀 NocoBase server running at: http://localhost:13000/
app_1  | info: BEGIN: GET / {"reqId":"0509e71e-57f4-4080-ba03-0e9256359c1f","timestamp":"2023-01-07T02:40:21.820Z"}
app_1  | warn: END: GET / {"req":{},"reqId":"0509e71e-57f4-4080-ba03-0e9256359c1f","res":{"status":404},"responseTime":10,"timestamp":"2023-01-07T02:40:21.829Z"}
app_1  | info: BEGIN: GET / {"reqId":"292e96fc-2c24-47ae-8293-8204d933a26f","timestamp":"2023-01-07T02:41:11.228Z"}
app_1  | warn: END: GET / {"req":{},"reqId":"292e96fc-2c24-47ae-8293-8204d933a26f","res":{"status":404},"responseTime":1,"timestamp":"2023-01-07T02:41:11.229Z"}
app_1  | info: BEGIN: GET / {"reqId":"b1e94ffe-bdb2-439b-afe2-b3ca6262e1fe","timestamp":"2023-01-07T02:42:27.431Z"}
app_1  | warn: END: GET / {"req":{},"reqId":"b1e94ffe-bdb2-439b-afe2-b3ca6262e1fe","res":{"status":404},"responseTime":2,"timestamp":"2023-01-07T02:42:27.432Z"}

```

**Comment by chenos** [comment]
```yml
version: "3"
networks:
  nocobase:
    driver: bridge
services:
  app:
    image: nocobase/nocobase:main
    networks:
      - nocobase
    environment:
      - LOCAL_STORAGE_BASE_URL=/storage/uploads
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - "13000:80"   # 查看一下这个端口映射的有没有问题，要 80 而不是 13000
```

查看一下 ports 映射的有没有问题，要 80 而不是 13000

**Comment by bonashen** [comment]
改成 80端口OK，谢谢指导！

```yaml
version: "3"
networks:
  nocobase:
    driver: bridge
services:
  app:
    image: nocobase/nocobase:latest
    networks:
      - nocobase
    environment:
      - LOCAL_STORAGE_BASE_URL=/storage/uploads
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - "13000:80"

```
