### ISSUE TITLE
docker compose down 耗时过久

### ISSUE THREAD

**Issue by MarshalW** [nocobase/nocobase#1581]
## Describe the bug

docker compose down 耗时过久，大约要1分钟

## Version

docker镜像，nocobase/nocobase:main

## How To Reproduce

```bash
# 使用 sqlite docker compose
cd docker/app-sqlite
docker compose up -d

# nocobase 正常运行后
docker compose down
[+] Running 2/2
 ⠿ Container app-sqlite-app-1   Removed                                         57.0s
 ⠿ Network app-sqlite_nocobase  Removed                                          0.3s
```

等待了57秒多才退出。

问题是因为退出信号没有正确传递给相关的 node.js 进程。

在 docker-compose.yml 文件中设置 `init` 属性可以解决问题：

```yml
version: "3"
networks:
  nocobase:
    driver: bridge
services:
  app:
    image: nocobase/nocobase:main
    networks:
      - nocobase
    environment:
      - LOCAL_STORAGE_BASE_URL=/storage/uploads
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - "13000:80"
    init: true  # <--- 增加的属性
```

## Expected behavior

退出耗时正常情况下不会超过5秒。

## Desktop (please complete the following information)

- OS: macOS 13.2.1 (22D68)
- docker desktop Version 4.16.1 (95567)
