### ISSUE TITLE
Issue with API documentation after enabling the multi-app plugin

### ISSUE THREAD

**Issue by wlkjunior** [nocobase/nocobase#2963]
**Problem Description:**

When using the API documentation in a Docker environment with Portainer and Traefik, I've noticed a significant issue after enabling the multi-app plugin and creating tables and collections in a new application. The API documentation works flawlessly in the main dashboard, but becomes inaccessible or non-functional in the newly created application.

**Steps to Reproduce:**

1- Enable the multi-app plugin in your environment.
2- Create a new application.
3- Create tables and collections in the new application.
4- Attempt to access the API documentation for the new application.
5- Notice that the documentation is not working as expected or is inaccessible.

**Technologies Used:**

Docker 24.0.6
Docker compose 1.29.2-1
Portainer Community Edition 2.19.1
Traefik 2.10.5

**Observed Behavior:**
The error only occurs in new applications created with the multi-app plugin, while the API documentation in the main dashboard functions correctly. It's important to note that the Ubuntu server in the environment has its firewall disabled.

**Screenshots or Code Snippets:**

Screenshot of the collection created in the new app

![image](https://github.com/nocobase/nocobase/assets/88210930/47f680b6-6114-4334-8dcf-03a8c85ac837)

**Example of my stack**

```
version: "3.7"

services:
  app:
    image: nocobase/nocobase:main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nocobase.rule=Host(`nocobase.mydomin.com.br`)" #Troque pelo seu domínio
      - "traefik.http.services.nocobase.loadbalancer.server.port=80"
      - "traefik.http.routers.nocobase.entrypoints=websecure"
      - "traefik.http.routers.nocobase.tls.certresolver=leresolver"
    environment:
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_DATABASE=nocobase
      - DB_USER=admin
      - DB_PASSWORD=mypassword
      - LOCAL_STORAGE_BASE_URL=/storage/uploads
      - APP_KEY=ABCD123456789
      - API_BASE_PATH=/api/
      - API_BASE_URL=nocobase.mydomin.com.br #Troque pelo seu domínio
      - PROXY_TARGET_URL=nocobase.mydomin.com.br #Troque pelo seu domínio
      - INIT_ROOT_EMAIL=email@mydomin.com.br #Troque pelo seu email
      - INIT_ROOT_PASSWORD=mypassword
      - INIT_ROOT_NICKNAME=Super Admin
      - INIT_ROOT_USERNAME=admin
    volumes:
      - nocobase_storage:/app/nocobase/storage

    depends_on:
      - postgres

  postgres:
    image: postgres:10
    restart: always
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: nocobase
      POSTGRES_PASSWORD: mypassword
    volumes:
      - nocobase_postgres:/var/lib/postgresql/data

networks:
  default:
    name: nocobase
    external: true

volumes:
  nocobase_postgres:
  nocobase_storage:
```

**Thank you for your work on this project. Your dedication is valued. I'm looking forward to a solution for this issue.**
