### ISSUE TITLE
Docker 部署后无法打开

### ISSUE THREAD

**Issue by Skywt2003** [nocobase/nocobase#455]
## Describe the bug

使用 Docker 部署后，用 Caddy 反向代理，打开页面白屏（右上角有三条空白的错误提示）。

容器 logs 如下：

```
❯ docker logs nocobase
nginx started
yarn run v1.22.18
$ nocobase db:auth --repeat=30
Connection has been established successfully.
Done in 12.71s.
yarn run v1.22.18
$ nocobase install -s
Connection has been established successfully.
Done in 11.75s.
yarn run v1.22.18
$ nocobase db:sync
db sync...
Done in 1.06s.
starting...
yarn run v1.22.18
$ nocobase start
Connection has been established successfully.
2022-06-02T01:55:15: PM2 log: Launching in no daemon mode
2022-06-02T01:55:15: PM2 log: App [index:0] starting in -fork mode-
2022-06-02T01:55:15: PM2 log: App [index:0] online
TypeError: Cannot read properties of undefined (reading 'field')
    at new BelongsToMany (/app/nocobase/node_modules/sequelize/lib/associations/belongs-to-many.js:81:69)
    at Function.belongsToMany (/app/nocobase/node_modules/sequelize/lib/associations/mixin.js:43:25)
    at BelongsToManyField.bind (/app/nocobase/node_modules/@nocobase/database/lib/fields/belongs-to-many-field.js:66:42)
    at Collection.<anonymous> (/app/nocobase/node_modules/@nocobase/database/lib/collection.js:166:13)
    at Collection.emit (node:events:527:28)
    at Collection.emit (node:domain:475:12)
    at Collection.setField (/app/nocobase/node_modules/@nocobase/database/lib/collection.js:200:10)
    at /app/nocobase/node_modules/@nocobase/plugin-collection-manager/lib/models/field.js:49:25
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/plugin-collection-manager/lib/models/field.js:18:103)
```

## Version

0.7.0-alpha.78

## How To Reproduce

使用 `docker-compose.yml`：

```yml
version: "3"

services:
  nocobase:
    image: nocobase/nocobase:0.7.0-alpha.78
    container_name: nocobase
    networks:
      - caddy
      - nocobase
    depends_on:
      - mariadb
    environment:
      - DB_DIALECT=mysql
      - DB_HOST=mariadb
      - DB_DATABASE=nocobase
      - DB_USER=nocobase
      - DB_PASSWORD=(PASSWORD)
      - LOCAL_STORAGE_BASE_URL=https://base.skywt.cn/storage/uploads
    #volumes:
    #  - /data/nocobase:/app/nocobase
    labels:
      caddy: base.skywt.cn
      caddy.reverse_proxy: "{{upstreams 80}}"
    restart: unless-stopped

networks:
  caddy:
    external: true
  nocobase:
    external: true
```

创建了 nocobase 这个 network，预先连接了数据库的容器（mariadb），数据库中已经创建好数据表。

caddy 负责反向代理，将容器的 80 端口反向代理到 https://base.skywt.cn。

## Expected behavior

能够正常访问使用。

## Screenshots

<img width="1440" alt="截屏2022-06-02 上午10 03 12" src="https://user-images.githubusercontent.com/29029278/171531909-a4a521bd-c38e-458b-bbba-04a2ab1d0945.png">

## Desktop

- OS: Debian
- Browser: Safari, Chrome
