### ISSUE TITLE
K3S部署卡在PM2 log: Launching in no daemon mode

### ISSUE THREAD

**Issue by tky753** [nocobase/nocobase#5334]
## * Describe the bug
想要尝试nocobase，直接源码运行试过可以，想要部署一个相对稳定环境继续研究学习。就部署在了测试环境(K3S)上。
昨天尝试了一天，一直卡在
![image](https://github.com/user-attachments/assets/0ed2b6f0-07a6-4a34-b399-f4352835955d)
浏览器打开请求报错：
![image](https://github.com/user-attachments/assets/e0f17b09-c3d0-4cc9-a39d-3b3a64c260e1)

## * Environment

- NocoBase version: `1.3.25-beta`

- Database type and version:  `mysql 8`
  

- OS: 

- Deployment Methods: `K3S`

- Docker image version: `1.3.25-beta`

- NodeJS version: -

## * How To Reproduce
部署yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nocobase
  labels:
    app: nocobase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nocobase
  template:
    metadata:
      labels:
        app: nocobase
    spec:
      containers:
      - name: nocobase
        image: registry.cn-shanghai.aliyuncs.com/nocobase/nocobase:1.3.25-beta
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nocobase-persistent-storage
          mountPath: /app/nocobase/storage
          subPath: nocobase
        env:
        - name: APP_KEY
          value: ******
        - name: DB_DIALECT
          value: mysql
        - name: DB_HOST
          value: "192.168.*.*"
        - name: DB_DATABASE
          value: nocobase
        - name: DB_USER
          value: ******
        - name: DB_PASSWORD
          value: ******
        - name: DB_UNDERSCORED
          value: "true"
        - name: DB_LOGGING
          value: "on"
        - name: TZ
          value: Asia/Shanghai
      volumes:
      - name: nocobase-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-smb
---
apiVersion: v1
kind: Service
metadata:
  name: nocobase-service
spec:
  type: NodePort
  selector:
    app: nocobase
  ports:
  - name: nocobase-service-port
    protocol: TCP
    port: 13000 
    nodePort: 13000 
    targetPort: 80
```
