### ISSUE TITLE
Static assets in storage/ can't get from browser. nginx return code 403.

### ISSUE THREAD

**Issue by Arkmusn** [nocobase/nocobase#5960]
## * Describe the bug

deploy in k3s.

Static assets in storage/ can't get from browser. nginx return code 403.

![image](https://github.com/user-attachments/assets/1844b466-5151-4254-99a9-cf9782b3c775)

Probably cause by user permission: the worker process of nginx is www-data

`ps aux`

![image](https://github.com/user-attachments/assets/5e7ebd79-16d9-46e0-8547-ea90466686eb)

`ls` on storage/

![image](https://github.com/user-attachments/assets/0ace324c-3709-4313-8467-772d900522e7)

## * Environment

- NocoBase version: not sure. I use docker image version 1.4.16

- Database type and version:  postgresql 16
  

- OS: k3s

- Deployment Methods: k3s

- Docker image version: 1.4.16

- NodeJS version:

## * How To Reproduce

manifest

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nocobase
spec:
  selector:
    matchLabels:
      app: nocobase
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: nocobase
    spec:
      containers:
        - name: nocobase
          image: registry.cn-shanghai.aliyuncs.com/nocobase/nocobase:1.4.16
          env:
            - name: TZ
              value: Asia/Shanghai
          envFrom:
            - configMapRef:
                name: nocobase-env
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /app/nocobase/storage
              name: nocobase-data
              subPath: nocobase
          livenessProbe:
            httpGet:
              port: http
            periodSeconds: 10
            failureThreshold: 2
          startupProbe:
            httpGet:
              port: http
            periodSeconds: 5
            failureThreshold: 24
      volumes:
        - name: nocobase-data
          persistentVolumeClaim:
            claimName: nfs-nas-apps
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nocobase-env
data:
  APP_KEY: "vmGLXJdRAecQAhEP"
  APP_PUBLIC_PATH: "/"
  DB_DIALECT: "postgres"
  DB_HOST: "postgresql"
  DB_DATABASE: "nocobase"
  DB_USER: "nocobase"
  DB_PASSWORD: "nocobase@postgresql"
  DB_TIMEZONE: "+08:00"
---
apiVersion: v1
kind: Service
metadata:
  name: nocobase
  labels:
    app: nocobase
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: nocobase
```
