### ISSUE TITLE
No UI Editor button at the upper right corner

### ISSUE THREAD

**Issue by hydra1983** [nocobase/nocobase#6852]
## * Describe the bug

No UI Editor button at the upper right corner

## * Environment

- NocoBase version: 1.6.28

- Database type and version: PostgreSQL16
  
- OS: MacOS

- Deployment Methods: Docker

- Docker image version: 1.6.28

## * How To Reproduce

create docker-compose.yml
```yaml
networks:
  nocobase:
    driver: bridge

services:
  app:
    image: registry.cn-shanghai.aliyuncs.com/nocobase/nocobase:1.6.28
    restart: always
    networks:
      - nocobase
    depends_on:
      - postgres
    environment:
      # 应用的密钥，用于生成用户 token 等
      # 如果 APP_KEY 修改了，旧的 token 也会随之失效
      # 可以是任意随机字符串，并确保不对外泄露
      - APP_KEY=your-secret-key
      # 数据库类型，支持 postgres, mysql, mariadb, sqlite
      - DB_DIALECT=postgres
      # 数据库主机，可以替换为已有的数据库服务器 IP
      - DB_HOST=postgres
      # Database port
      - DB_PORT=5432
      # 数据库名
      - DB_DATABASE=nocobase
      # 数据库用户
      - DB_USER=nocobase
      # 数据库密码
      - DB_PASSWORD=nocobase
      # 时区
      - TZ=Asia/Shanghai
      # 商业插件，使用 docker network ls 的账号信息
      - NOCOBASE_PKG_USERNAME=
      - NOCOBASE_PKG_PASSWORD=

    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - '13000:80'
    # init: true

  # 如果使用已有数据库服务，可以不启动 postgres
  postgres:
    image: registry.cn-shanghai.aliyuncs.com/nocobase/postgres:16
    restart: always
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_USER: nocobase
      POSTGRES_DB: nocobase
      POSTGRES_PASSWORD: nocobase
    volumes:
      - ./storage/db/postgres:/var/lib/postgresql/data
    networks:
      - nocobase
```

run 
```
docker compose up -d
```

## Expected behavior

After login, there should be a UI Editor button at the upper right corner.

## Screenshots

![Image](https://github.com/user-attachments/assets/c5d2621f-525c-4740-98d0-61a46e9b0569)

## Logs

None.
